
### Fetch All Tasks
GET http://www.localhost:3000/tasks 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impld2VsIiwiaWF0IjoxNjAwMDE2MzY0LCJleHAiOjE2MDAwMTk5NjR9.wzoam8Sq7OlUH-CpMPbCFicMP0QNOUE0GdZSZ4itZf0

###
GET http://www.localhost:3000/tasks/getfile/2


### Create Task 

POST http://www.localhost:3000/tasks
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdhbGliIiwiaWF0IjoxNjAwMDE3MDI1LCJleHAiOjE2MDAwMjA2MjV9.KLgt81iNMhWVMJ73QSv2xlExClatZPeflGulHczGFfU

{
    "title":"Python",
    "description":"Eu aliquip duis adipisicing sit ea duis nostrud incididunt consequat."
    
}

### Get Task by id
GET http://www.localhost:3000/tasks/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impld2VsIiwiaWF0IjoxNjAwMDE2MzY0LCJleHAiOjE2MDAwMTk5NjR9.wzoam8Sq7OlUH-CpMPbCFicMP0QNOUE0GdZSZ4itZf0

### Update Status 
PATCH  http://www.localhost:3000/tasks/7
Content-Type: application/json

{
    "status":"DONE"
}

### Search and Filter 
GET http://www.localhost:3000/tasks?status=DONE


###Delete Task

DELETE http://www.localhost:3000/tasks/2