
### Fetch All Tasks
GET http://www.localhost:3000/tasks 


### Create Task 
POST http://www.localhost:3000/tasks
content-type: application/json

{
    "title": "JqUery",
    "description":"Occaecat consequat id elit voluptate id est est et nulla non aute mollit." 
}

### Get Task by id
GET http://www.localhost:3000/tasks/2

### Update Status 
PATCH  http://www.localhost:3000/tasks/4
Content-Type: application/json

{
    "status":"DONE"
}

### Search and Filter 
GET http://www.localhost:3000/tasks?status=OPEN&search=Py


###Delete Task

DELETE http://www.localhost:3000/tasks/2